### ISSUE TITLE
mise en place server side

### ISSUE THREAD

**Issue by LeVraiPicou** [monkey-corp/MonkeyCorp.fr#24]
## Prérequis
Ticket fini https://github.com/monkey-corp/MonkeyCorp.fr/issues/22

## Demande
faire le serveur side

## À faire
création bdd (MySql)

**Comment by JMazat** [comment]
Il faut se mettre d'accord sur les ressources avant de faire la BDD/API.

Je fais une propal de conception cette aprem normalement. Je posterai ici (je le notifierai sur discord).

**Comment by LeVraiPicou** [comment]
Merci c'est vraiment quali juste quelques retours : 

### News

ce serais bien d'avoir l'auteur de l'article de dispo 

### fight

Peut être sources

### encyclopedia

Prévoir champs "annecdote" (pour mettre des trucs simpas/ecologie ou quoi) default NULL

### image

Il faudrait le nom ou le path de l'image 

### person

Il manque email (required), genre (required), tel (Default NULL)

### General

Il faut penser à mettre des champs created_at et updated_at sur tout afin de pouvoir trier le mieux possible plus tard

**Comment by JMazat** [comment]
A partir de maintenant, merci de se référer au ticket #41 pour la conception.
